content_api:
    service:
        prefix: '%env(SERVICE_NAME)%'
        include_prefix: false
        items: libero.content_store.items
        put_workflow: libero.content_store.put

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    libero.content_store.items:
        class: Libero\ContentApiBundle\Adapter\FilesystemItems
        arguments:
            - '%kernel.data_dir%'
