content_api:
    service:
        prefix: '%env(SERVICE_NAME)%'
        include_prefix: false
        items: libero.content_store.items

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    libero.content_store.items:
        class: Libero\ContentApiBundle\Adapter\DoctrineItems
        arguments:
            - '@doctrine.dbal.default_connection'
            - 'items'

    libero.content_store.items.schema:
        class: Doctrine\DBAL\Schema\Schema
        factory: 'libero.content_store.items:getSchema'

    libero.content_store.items.schema_provider:
        class: Doctrine\Migrations\Provider\StubSchemaProvider
        arguments:
            - '@libero.content_store.items.schema'
