oneup_flysystem:
    adapters:
        default_adapter:
            local:
                directory: '%env(ASSETS_PATH)%'
    filesystems:
        default_filesystem:
            adapter: default_adapter
            alias: League\Flysystem\FilesystemInterface
            plugins:
                - Libero\ContentStore\Flysystem\HttpUrlPlugin
