oneup_flysystem:
    adapters:
        assets_adapter:
            local:
                directory: '%env(ASSETS_PATH)%'
    filesystems:
        assets:
            adapter: assets_adapter
            plugins:
                - Libero\ContentStore\Flysystem\HttpUrlPlugin
