parameters:
    env(S3_ENDPOINT): ~
    env(S3_PREFIX): ~

oneup_flysystem:
    adapters:
        assets_adapter:
            awss3v3:
                client: oneup_flysystem.assets_adapter.s3_client
                bucket: '%env(S3_BUCKET)%'
                prefix: '%env(S3_PREFIX)%'
    filesystems:
        assets:
            adapter: assets_adapter
            plugins:
                - oneup_flysystem.assets_filesystem.plugin.http_url

services:

    oneup_flysystem.assets_adapter.s3_client:
        class: Aws\S3\S3Client
        arguments:
            - version: '2006-03-01'
              region: '%env(S3_REGION)%'
              endpoint: '%env(S3_ENDPOINT)%'
              use_path_style_endpoint: true
              credentials:
                  key: '%env(S3_KEY)%'
                  secret: '%env(S3_SECRET)%'

    oneup_flysystem.assets_filesystem.plugin.http_url:
        class: Libero\ContentStore\Flysystem\HttpUrlPlugin
        arguments:
            - '%env(ASSETS_URI)%'
