oneup_flysystem:
    adapters:
        assets_adapter:
            local:
                directory: '%env(ASSETS_PATH)%'
    filesystems:
        assets:
            adapter: assets_adapter
            plugins:
                - oneup_flysystem.assets_filesystem.plugin.http_url

services:

    oneup_flysystem.assets_filesystem.plugin.http_url:
        class: Libero\ContentStore\Flysystem\HttpUrlPlugin
        arguments:
            - '%env(ASSETS_URI)%'
