framework:
    workflows:
        libero.content_store.put:
            type: workflow
            marking_store:
                type: single_state
                arguments:
                    - state
            supports:
                - Libero\ContentApiBundle\Model\PutTask
            places:
                - start
                - needs_validation
                - needs_manipulation
                - end
            transitions:
                start:
                    from: start
                    to: needs_validation
                validate:
                    from: needs_validation
                    to: needs_manipulation
                manipulate:
                    from: needs_manipulation
                    to: end
