version: '3.4'

services:
    db:
        image: postgres:11.2-alpine
    app:
        build:
            context: .
            target: prod
        environment:
            APP_SECRET:
            DEFAULT_LOCALE:
            SERVICE_NAME:
            DATABASE_URL: pgsql://postgres:@db:5432/postgres
            ASSETS_URI: http://localhost:8080/assets/
            ASSETS_PATH: /app/var/assets/
        command: >
            sh -c '
                while ! nc db 5432; do sleep 1; done
                bin/console doctrine:migrations:migrate --no-interaction
                php-fpm
            '
        volumes:
            - assets:/app/var/assets/
        image: libero/content-store:${IMAGE_TAG:-master}
        depends_on:
            - db
    web:
        image: nginx:1.15.8-alpine
        volumes:
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - assets:/app/public/assets/
        ports:
            - 8080:80
        depends_on:
            - app

volumes:
    assets:
