version: '3.4'

services:
    db:
        image: postgres:11.2-alpine
    s3:
        image: minio/minio:RELEASE.2019-05-02T19-07-09Z
        environment:
            MINIO_ACCESS_KEY: &AWSKey AKIAIOSFODNN7EXAMPLE
            MINIO_SECRET_KEY: &AWSSecret wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
            MINIO_REGION: &AWSRegion us-east-1
        command: server /app
        ports:
            - 8081:9000
    s3-bucket:
        image: minio/mc:RELEASE.2019-05-01T23-27-44Z
        environment:
            AWS_ACCESS_KEY_ID: *AWSKey
            AWS_SECRET_ACCESS_KEY: *AWSSecret
            AWS_DEFAULT_REGION: *AWSRegion
            S3_BUCKET: &S3Bucket bucket
        entrypoint: sh
        command: >
            -ce '
                while ! nc s3 9000; do sleep 1; done
                mc config host add minio http://s3:9000 $${AWS_ACCESS_KEY_ID} $${AWS_SECRET_ACCESS_KEY}
                mc mb minio/$${S3_BUCKET} --region $${AWS_DEFAULT_REGION}
                mc policy download minio/$${S3_BUCKET}
            '
        depends_on:
            - s3
    app:
        build:
            context: .
            target: prod
        environment:
            APP_SECRET:
            DEFAULT_LOCALE:
            SERVICE_NAME:
            DATABASE_URL: pgsql://postgres:@db:5432/postgres
            AWS_ACCESS_KEY_ID: *AWSKey
            AWS_SECRET_ACCESS_KEY: *AWSSecret
            AWS_DEFAULT_REGION: *AWSRegion
            S3_ENDPOINT: http://s3:9000
            S3_BUCKET: *S3Bucket
            S3_PATH_STYLE_ENDPOINT: 'true'
        command: >
            sh -c '
                while ! nc db 5432; do sleep 1; done
                bin/console doctrine:migrations:migrate --no-interaction
                php-fpm
            '
        image: libero/content-store:${IMAGE_TAG:-master}
        depends_on:
            - db
            - s3-bucket
    web:
        image: nginx:1.15.8-alpine
        volumes:
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./public/:/app/public/
        ports:
            - 8080:80
        depends_on:
            - app
