parameters:
    env(DEFAULT_LOCALE): 'en'
    env(SERVICE_NAME): 'articles'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Libero\ContentStore\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php}'

    Libero\JatsContentWorkflow\Workflow\MoveJatsAssets:
        arguments:
            - '%env(ASSETS_ORIGIN_WHITELIST)%'
            - '%env(ASSETS_PUBLIC_URI)%'
            - '@oneup_flysystem.assets_filesystem'
            - '@csa_guzzle.client.asset_download'
        tags:
            - name: 'kernel.event_listener'
              event: 'workflow.libero.content_store.put.transition.manipulate'
              method: 'onManipulate'

    libero.content_store.s3_handler:
        class: Aws\Handler\GuzzleV6\GuzzleHandler
        arguments:
            - '@csa_guzzle.client.s3'
