parameters:
    env(DEFAULT_LOCALE): 'en'
    env(SERVICE_NAME): 'articles'
    kernel.data_dir: '%kernel.project_dir%/data'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Libero\ContentStore\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php}'
