parameters:
    env(ASSETS_ORIGIN): '~.+~'
    env(DEFAULT_LOCALE): 'en'
    env(SERVICE_NAME): 'articles'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Libero\ContentStore\:
        resource: '../src/*'
        exclude: '../src/{functions.php,Kernel.php}'

    Libero\ContentStore\Workflow\MoveJatsAssets:
        arguments:
            - '%env(ASSETS_ORIGIN)%'
            - '%env(S3_PUBLIC_ENDPOINT)%'
            - '@oneup_flysystem.assets_filesystem'
