parameters:
    env(DEFAULT_LOCALE): 'en'
    kernel.data_dir: '%kernel.project_dir%/data'
    service_name: 'articles'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Libero\ContentStore\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php}'
